package tourism.exporter.distance.kk

import tourism.exporter.Distance
import tourism.exporter.RunPoint
import tourism.exporter.TechnicalPoint

val KK25Pair =
    Distance(
        name = "КК св 03.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "5",
        orgeoCategories = listOf("М" to listOf("МУЖ_5"), "Ж" to listOf("ЖЕН_5")),
        points =
            listOf(
                RunPoint(61, 70),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(62, 500),
                TechnicalPoint("Дом II", 72, failureCode = 102),
                RunPoint(63, 250),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(64, 140),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(65, 440),
                TechnicalPoint("Маятник", 75, failureCode = 105),
                RunPoint(100),
                RunPoint(61, 300),
                TechnicalPoint("Дом III", 71, failureCode = 101),
                RunPoint("FIN", length = 110, "000"),
            ),
    )

val KK25Short =
    Distance(
        name = "КК лч кор 04.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "2",
        orgeoCategories = listOf("М" to listOf("5_МУЖ"), "Ж" to listOf("5_ЖЕН")),
        points =
            listOf(
                RunPoint(61, 70),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(62, 500),
                TechnicalPoint("Дом II", 72, failureCode = 102),
                RunPoint(63, 250),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(64, 140),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(65, 440),
                TechnicalPoint("Маятник", 75, failureCode = 105),
                RunPoint(100),
                RunPoint(61, 300),
                TechnicalPoint("Дом III", 71, failureCode = 101),
                RunPoint(-1, length = 110, "000"),
            ),
    )

val KK25LongM =
    Distance(
        name = "КК лч дл М 05.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "3",
        orgeoCategories = listOf("М" to listOf("5_МУЖ")),
        points =
            listOf(
                RunPoint(62),
                TechnicalPoint("Б.Дом", 72, failureCode = 102),
                RunPoint(31),
                RunPoint(40),
                RunPoint(32),
                RunPoint(33),
                RunPoint(34),
                RunPoint(40),
                RunPoint(36),
                RunPoint(38),
                RunPoint(40),
                RunPoint(45),
                RunPoint(64),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(63),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(39),
                RunPoint(38),
                RunPoint(37),
                RunPoint(61),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(52),
                RunPoint(66),
                TechnicalPoint("Маятник", 76, failureCode = 106),
                RunPoint(49),
                RunPoint(48),
                RunPoint(65),
                TechnicalPoint("Маятник II", 75, failureCode = 105),
                RunPoint(46),
                RunPoint(53),
                RunPoint(50),
                RunPoint(-1, length = 8800, "000"),
            ),
        seeding = listOf(listOf(36, 38, 40).map { it.toString() } to listOf(32, 33, 34, 40).map { it.toString() })
    )

val KK25LongW =
    Distance(
        name = "КК лч дл Ж 05.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "3",
        orgeoCategories = listOf("Ж" to listOf("5_ЖЕН")),
        points =
            listOf(
                RunPoint(62),
                TechnicalPoint("Б.Дом", 72, failureCode = 102),
                RunPoint(31),
                RunPoint(35),
                RunPoint(36),
                RunPoint(45),
                RunPoint(64),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(63),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(41),
                RunPoint(42),
                RunPoint(43),
                RunPoint(41),
                RunPoint(40),
                RunPoint(39),
                RunPoint(41),
                RunPoint(61),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(52),
                RunPoint(66),
                TechnicalPoint("Маятник", 76, failureCode = 106),
                RunPoint(49),
                RunPoint(47),
                RunPoint(65),
                TechnicalPoint("Маятник II", 75, failureCode = 105),
                RunPoint(46),
                RunPoint(53),
                RunPoint(50),
                RunPoint(-1, length = 7300, "000"),
            ),
        seeding = listOf(listOf(40, 39, 41).map { it.toString() } to listOf(42, 43, 41).map { it.toString() })
    )

val KK25GroupM =
    Distance(
        name = "КК гр дл М 06.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "4",
        orgeoCategories = listOf("М" to listOf("5_МУЖ")),
        points =
            listOf(
                RunPoint(67),
                TechnicalPoint("Лка", 77, failureCode = 107),
                RunPoint(31),
                RunPoint(32),
                RunPoint(33),
                RunPoint(34),
                RunPoint(35),
                RunPoint(38),
                RunPoint(64),
                TechnicalPoint("Навеска", 74, failureCode = 104),
                RunPoint(39),
                RunPoint(69),
                TechnicalPoint("Спуск", 79, failureCode = 109),
                RunPoint(41),
                RunPoint(68),
                TechnicalPoint("Навеска", 78, failureCode = 108),
                RunPoint(42),
                RunPoint(43),
                RunPoint(60),
                TechnicalPoint("Брод", 70, failureCode = 100),
                RunPoint(50),
                RunPoint(61),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(48),
                RunPoint(66),
                TechnicalPoint("Маятник", 76, failureCode = 106),
                RunPoint(62),
                TechnicalPoint("Б.Дом", 72, failureCode = 102),
                RunPoint(63),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(50),
                RunPoint(-1, length = 13700, "000"),
            ),
    )

val KK25GroupW =
    Distance(
        name = "КК гр дл Ж 06.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "4",
        orgeoCategories = listOf("Ж" to listOf("5_ЖЕН")),
        points =
            listOf(
                RunPoint(67),
                TechnicalPoint("Лка", 77, failureCode = 107),
                RunPoint(31),
                RunPoint(32),
                RunPoint(33),
                RunPoint(34),
                RunPoint(36),
                RunPoint(37),
                RunPoint(64),
                TechnicalPoint("Навеска", 74, failureCode = 104),
                RunPoint(40),
                RunPoint(69),
                TechnicalPoint("Спуск", 79, failureCode = 109),
                RunPoint(41),
                RunPoint(68),
                TechnicalPoint("Навеска", 78, failureCode = 108),
                RunPoint(44),
                RunPoint(60),
                TechnicalPoint("Брод", 70, failureCode = 100),
                RunPoint(50),
                RunPoint(61),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(48),
                RunPoint(66),
                TechnicalPoint("Маятник", 76, failureCode = 106),
                RunPoint(62),
                TechnicalPoint("Б.Дом", 72, failureCode = 102),
                RunPoint(63),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(50),
                RunPoint(-1, length = 13100, "000"),
            ),
    )

val KK25Pair4 =
    Distance(
        name = "КК св 4кл 03.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "5",
        orgeoCategories = listOf("М" to listOf("ЮНР_4"), "Ж" to listOf("ЮНРК_4")),
        points =
            listOf(
                RunPoint(61, 70),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(62, 500),
                TechnicalPoint("Дом II", 72, failureCode = 102),
                RunPoint(63, 250),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(64, 140),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(65, 440),
                TechnicalPoint("Маятник", 75, failureCode = 105),
                RunPoint(100),
                RunPoint(61, 300),
                TechnicalPoint("Лка", 71, failureCode = 101),
                RunPoint("FIN", length = 110, "000"),
            ),
    )

val KK25Short4 =
    Distance(
        name = "КК лч кор 4кл 04.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "2",
        orgeoCategories = listOf("М" to listOf("4_ЮНР"), "Ж" to listOf("4_ЮНРК")),
        points =
            listOf(
                RunPoint(61, 70),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(62, 500),
                TechnicalPoint("Дом II", 72, failureCode = 102),
                RunPoint(63, 250),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(64, 140),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(65, 440),
                TechnicalPoint("Маятник", 75, failureCode = 105),
                RunPoint(100),
                RunPoint(61, 300),
                TechnicalPoint("Дом III", 71, failureCode = 101),
                RunPoint(-1, length = 110, "000"),
            ),
    )

val KK25Long4M =
    Distance(
        name = "КК лч дл 4кл М 05.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "3",
        orgeoCategories = listOf("М" to listOf("4_ЮНР")),
        points =
            listOf(
                RunPoint(62),
                TechnicalPoint("Б.Дом", 72, failureCode = 102),
                RunPoint(32),
                RunPoint(33),
                RunPoint(36),
                RunPoint(38),
                RunPoint(45),
                RunPoint(64),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(63),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(40),
                RunPoint(37),
                RunPoint(42),
                RunPoint(61),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(66),
                TechnicalPoint("Маятник", 76, failureCode = 106),
                RunPoint(49),
                RunPoint(48),
                RunPoint(65),
                TechnicalPoint("Маятник II", 75, failureCode = 105),
                RunPoint(46),
                RunPoint(53),
                RunPoint(50),
                RunPoint(-1, length = 7200, "000"),
            ),
    )

val KK25Long4W =
    Distance(
        name = "КК лч дл 4кл Ж 05.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "3",
        orgeoCategories = listOf("Ж" to listOf("4_ЮНРК")),
        points =
            listOf(
                RunPoint(62),
                TechnicalPoint("Б.Дом", 72, failureCode = 102),
                RunPoint(31),
                RunPoint(35),
                RunPoint(36),
                RunPoint(45),
                RunPoint(64),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(63),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(41),
                RunPoint(42),
                RunPoint(61),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(66),
                TechnicalPoint("Маятник", 76, failureCode = 106),
                RunPoint(49),
                RunPoint(47),
                RunPoint(65),
                TechnicalPoint("Маятник II", 75, failureCode = 105),
                RunPoint(46),
                RunPoint(53),
                RunPoint(50),
                RunPoint(-1, length = 6300, "000"),
            ),
    )

val KK25Group4M =
    Distance(
        name = "КК гр дл 4кл М 06.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "4",
        orgeoCategories = listOf("М" to listOf("4_ЮНР")),
        points =
            listOf(
                RunPoint(51),
                RunPoint(49),
                RunPoint(66),
                TechnicalPoint("Маятник", 76, failureCode = 106),
                RunPoint(45),
                RunPoint(39),
                RunPoint(69),
                TechnicalPoint("Спуск", 79, failureCode = 109),
                RunPoint(41),
                RunPoint(68),
                TechnicalPoint("Навеска", 78, failureCode = 108),
                RunPoint(42),
                RunPoint(43),
                RunPoint(60),
                TechnicalPoint("Брод", 70, failureCode = 100),
                RunPoint(50),
                RunPoint(61),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(62),
                TechnicalPoint("Б.Дом", 72, failureCode = 102),
                RunPoint(54),
                RunPoint(55),
                RunPoint(63),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(50),
                RunPoint(-1, length = 9600, "000"),
            ),
    )

val KK25Group4W =
    Distance(
        name = "КК гр дл 4кл Ж 06.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "4",
        orgeoCategories = listOf("Ж" to listOf("4_ЮНРК")),
        points =
            listOf(
                RunPoint(51),
                RunPoint(49),
                RunPoint(66),
                TechnicalPoint("Маятник", 76, failureCode = 106),
                RunPoint(45),
                RunPoint(40),
                RunPoint(69),
                TechnicalPoint("Спуск", 79, failureCode = 109),
                RunPoint(41),
                RunPoint(68),
                TechnicalPoint("Навеска", 78, failureCode = 108),
                RunPoint(44),
                RunPoint(60),
                TechnicalPoint("Брод", 70, failureCode = 100),
                RunPoint(50),
                RunPoint(61),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(62),
                TechnicalPoint("Б.Дом", 72, failureCode = 102),
                RunPoint(63),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(50),
                RunPoint(-1, length = 7600, "000"),
            ),
    )

val KK25Pair3 =
    Distance(
        name = "КК св 3кл 03.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "5",
        orgeoCategories = listOf("М" to listOf("ЮН_3"), "Ж" to listOf("ДЕВ_3")),
        points =
            listOf(
                RunPoint(61, 70),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(62, 500),
                TechnicalPoint("Дом II", 72, failureCode = 102),
                RunPoint(63, 250),
                TechnicalPoint("IIки", 83, failureCode = 103),
                RunPoint(64, 80),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(65, 440),
                TechnicalPoint("Маятник", 75, failureCode = 105),
                RunPoint(100),
                RunPoint(61, 300),
                TechnicalPoint("Лка", 71, failureCode = 101),
                RunPoint("FIN", length = 110, "000"),
            ),
    )

val KK25Short3 =
    Distance(
        name = "КК лч кор 3кл 04.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "2",
        orgeoCategories = listOf("М" to listOf("3_ЮН"), "Ж" to listOf("3_ДЕВ")),
        points =
            listOf(
                RunPoint(61, 70),
                TechnicalPoint("Дом", 71, failureCode = 101),
                RunPoint(62, 500),
                TechnicalPoint("Дом II", 72, failureCode = 102),
                RunPoint(63, 250),
                TechnicalPoint("IIки", 83, failureCode = 103),
                RunPoint(64, 80),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(65, 440),
                TechnicalPoint("Маятник", 75, failureCode = 105),
                RunPoint(100),
                RunPoint(61, 300),
                TechnicalPoint("Дом III", 71, failureCode = 101),
                RunPoint(-1, length = 110, "000"),
            ),
    )

val KK25Long3M =
    Distance(
        name = "КК лч дл 3кл М 05.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "3",
        orgeoCategories = listOf("М" to listOf("3_ЮН")),
        points =
            listOf(
                RunPoint(51),
                RunPoint(48),
                RunPoint(49),
                RunPoint(66),
                TechnicalPoint("Маятник", 76, failureCode = 106),
                RunPoint(52),
                RunPoint(61),
                TechnicalPoint("Лка", 71, failureCode = 101),
                RunPoint(62),
                TechnicalPoint("Дом", 72, failureCode = 102),
                RunPoint(31),
                RunPoint(34),
                RunPoint(39),
                RunPoint(46),
                RunPoint(64),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(63),
                TechnicalPoint("IIки", 83, failureCode = 103),
                RunPoint(44),
                RunPoint(45),
                RunPoint(50),
                RunPoint(-1, length = 5500, "000"),
            ),
    )

val KK25Long3W =
    Distance(
        name = "КК лч дл 3кл Ж 05.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "3",
        orgeoCategories = listOf("Ж" to listOf("3_ДЕВ")),
        points =
            listOf(
                RunPoint(51),
                RunPoint(47),
                RunPoint(49),
                RunPoint(66),
                TechnicalPoint("Маятник", 76, failureCode = 106),
                RunPoint(52),
                RunPoint(61),
                TechnicalPoint("Лка", 71, failureCode = 101),
                RunPoint(62),
                TechnicalPoint("Дом", 72, failureCode = 102),
                RunPoint(31),
                RunPoint(40),
                RunPoint(42),
                RunPoint(46),
                RunPoint(64),
                TechnicalPoint("Спуск", 74, failureCode = 104),
                RunPoint(63),
                TechnicalPoint("IIки", 83, failureCode = 103),
                RunPoint(44),
                RunPoint(45),
                RunPoint(50),
                RunPoint(-1, length = 5100, "000"),
            ),
    )

val KK25Group3M =
    Distance(
        name = "КК гр дл 3кл М 06.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "4",
        orgeoCategories = listOf("М" to listOf("3_ЮН")),
        points =
            listOf(
                RunPoint(65, 440),
                TechnicalPoint("Маятник", 75, failureCode = 105),
                RunPoint(49),
                RunPoint(48),
                RunPoint(47),
                RunPoint(50),
                RunPoint(61),
                TechnicalPoint("Лка", 71, failureCode = 101),
                RunPoint(62),
                TechnicalPoint("Лка II", 72, failureCode = 102),
                RunPoint(56),
                RunPoint(52),
                RunPoint(53),
                RunPoint(54),
                RunPoint(63),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(50),
                RunPoint(-1, length = 5400, "000"),
            ),
    )

val KK25Group3W =
    Distance(
        name = "КК гр дл 3кл Ж 06.07.25",
        orgeoEventId = "44488",
        orgeoSubId = "4",
        orgeoCategories = listOf("Ж" to listOf("3_ДЕВ")),
        points =
            listOf(
                RunPoint(65, 440),
                TechnicalPoint("Маятник", 75, failureCode = 105),
                RunPoint(49),
                RunPoint(48),
                RunPoint(47),
                RunPoint(50),
                RunPoint(61),
                TechnicalPoint("Лка", 71, failureCode = 101),
                RunPoint(62),
                TechnicalPoint("Лка II", 72, failureCode = 102),
                RunPoint(54),
                RunPoint(53),
                RunPoint(52),
                RunPoint(63),
                TechnicalPoint("IIки", 73, failureCode = 103),
                RunPoint(50),
                RunPoint(-1, length = 5100, "000"),
            ),
    )
